### ISSUE TITLE
winit example panics on macOS

### ISSUE THREAD

**Issue by johanholmerin** [tauri-apps/wry#1318]
**Describe the bug**
The winit example panics on macOS whenever the window is unfocused. I've tried updating winit but get the same error.

**Steps To Reproduce**
Run `cargo run --example winit` and then focus another window

**Expected behavior**
The example not to panic

**Screenshots**

**Platform and Versions (please complete the following information):**
OS: macOS Sonoma 14.5
Rustc: 1.79.0

**Additional context**
```log
thread 'main' panicked at /Users/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/runtime/mod.rs:1015:17:
ivar _state not found on class WryWebViewParent
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: objc2::runtime::ivar_offset
             at /Users/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/runtime/mod.rs:1015:17
   3: objc2::declare::ivar::IvarType::__offset
             at /Users/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/declare/ivar.rs:97:9
   4: objc2::declare::ivar::Ivar<T>::as_inner_ptr
             at /Users/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/declare/ivar.rs:218:31
   5: <objc2::declare::ivar::Ivar<T> as core::ops::deref::Deref>::deref
             at /Users/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/declare/ivar.rs:271:18
   6: winit::platform_impl::platform::view::WinitView::reset_modifiers
             at /Users/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/view.rs:905:13
   7: winit::platform_impl::platform::window_delegate::WinitWindowDelegate::window_did_resign_key
             at /Users/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/window_delegate.rs:180:13
```

**Comment by johanholmerin** [comment]
Confirmed to still be an issue with `build` on 0.51.2. `build_as_child` works.

**Comment by JJJ** [comment]
I retested this on current `dev` at `d8fe88d` using macOS 26.6.2. The `winit` example built and remained stable while repeatedly moving focus to Finder and Safari.

The example now uses `WebViewBuilder::build_as_child(&window)`, added by #1323 in commit `86faa70` specifically as the workaround for this crash. I couldn't reproduce the original panic on the current example, so this appears resolved and can likely be closed.
