### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by matthunz** [tauri-apps/wry#834]
**Describe the bug**
```
error: failed to run custom build command for `wry v0.23.4`
> :app:rustBuildArm64Release
Caused by:
  process didn't exit successfully: `/Users/matt/Documents/chords/src-tauri/target/release/build/wry-c0dd70ce73328e8e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=WRY_ANDROID_REVERSED_DOMAIN
  cargo:rerun-if-env-changed=WRY_ANDROID_APP_NAME_SNAKE_CASE
  cargo:rerun-if-env-changed=WRY_ANDROID_KOTLIN_FILES_OUT_DIR

  --- stderr
  thread 'main' panicked at 'Failed to canonicalize `WRY_ANDROID_KOTLIN_FILES_OUT_DIR` path /Users/matt/Documents/chords/src-tauri/gen/android/chords/app/src/main/java/com/chords/chords/generated', /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.23.4/build.rs:37:11
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
       Error `Failed to run `cargo build`: Command "cargo build --package chords --manifest-path /Users/matt/Documents/chords/src-tauri/Cargo.toml --target aarch64-linux-android --features custom-protocol --release --color always" didn't complete successfully, exiting with code 101.

FAILURE: Build failed with an exception.
```

**Steps To Reproduce**
I built this with `npm run tauri android build`

**Expected behavior**
It looks like a problem in `build.rs` that should be fixed to correctly compile for android.

**Platform and Versions (please complete the following information):**
OS: Android
Rustc: latest (nightly)

**Would you assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

**Additional context**

**Comment by amrbashir** [comment]
looks like you didn't call `tauri android init` first

**Comment by logankeenan** [comment]
@amrbashir 
`tauri android init` did not fix this issue for me.  

I did notice you recently made [changes](https://github.com/tauri-apps/tauri-mobile/blob/cceb9d8c99082656c12fbcde1948a7e3aef38fa7/CHANGELOG.md#changelog) to tauri-mobile related to `wry`. So I installed the latest version of the tauri-cli (`cargo install tauri-cli --git https://github.com/tauri-apps/tauri.git/ --branch next`) which included tauri-mobile 1.5.  I deleted the `/gen` directory and  ran `tauri android init` to recreate it.  However, I'm still getting the same error.  I'm also in the discord channel if that's a better place to triage. 


I've uploaded the repo [here.](https://github.com/logankeenan/mobile-test)  For context, I'm trying to get the basic mobile Tauri app running before integrating it with my current Tauri app.


* rustc 1.66.1 (90743e729 2023-01-10)
* tauri-cli 2.0.0-alpha.1


# Error 
```
error: failed to run custom build command for `wry v0.23.4`

Caused by:
  process didn't exit successfully: `/Users/logankeenan/Developer/mobile-test/src-tauri/target/debug/build/wry-807c9e3aaf451b92/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=WRY_ANDROID_REVERSED_DOMAIN
  cargo:rerun-if-env-changed=WRY_ANDROID_APP_NAME_SNAKE_CASE
  cargo:rerun-if-env-changed=WRY_ANDROID_KOTLIN_FILES_OUT_DIR

  --- stderr
  thread 'main' panicked at '`WRY_ANDROID_REVERSED_DOMAIN` is not set, which is needed to generate the kotlin files for android.', /Users/logankeenan/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.23.4/build.rs:19:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
       Error `Failed to run `cargo build`: Command "cargo build --package mobile-test --manifest-path /Users/logankeenan/Developer/mobile-test/src-tauri/Cargo.toml --target x86_64-linux-android --no-default-features --color always" didn't complete successfully, exiting with code 101.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:rustBuildX86_64Debug'.
> Process 'command '/Users/logankeenan/.cargo/bin/cargo-tauri'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
       Error Failed to assemble APK: Command "/Users/logankeenan/Developer/mobile-test/src-tauri/gen/android/mobile_test/gradlew --project-dir /Users/logankeenan/Developer/mobile-test/src-tauri/gen/android/mobile_test assembleX86_64Debug --warn" didn't complete successfully, exiting with code 1.
 ```

**Comment by amrbashir** [comment]
this new error suggests a version mismatch between versions, probably the cli is built locally or from git and the tauri crates are pulled from crates.io. you need to either use all from git or all from crates.io

**Comment by logankeenan** [comment]
Thank you! That worked!

Here's the [repo](https://github.com/logankeenan/mobile-test/tree/2e6f7baea62f4ccde5d37ec56c2938c3740464db) working for anyone else that runs into the same issue
